"""empty message

Revision ID: 910354f7d3a1
Revises: f3dff933274d
Create Date: 2024-09-09 11:06:46.437221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910354f7d3a1'
down_revision = 'f3dff933274d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
